sudo: true
dist: trusty
language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: test
      script: 
      - rm -r settings.json
      - wget $link
      - cat settings.json
      - node copy.js clone
