sudo: true
dist: trusty
language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: test
      script: 
      - sudo apt update
      - sudo apt install pastebinit -y
      - rm -r settings.json
      - wget $link
      - node copy.js clone
      - ls
      - cat guildData.json | pastebinit
